### PR TITLE
Added topic Linux File Permissions

### PR DESCRIPTION
**Pull request by Cipher7**
Hey,
I was going through your notes and found this section was empty! Hence decided to contribute. I have written this topic to the best of my knowledge and have also checked my grammar and crossed checked some essential stuff. You can reach me out via discord or twitter, both id's are in my profile. 
Thank you!

### CODE REVIEW

**Comment by zweilosec** [comment]
Hey, thanks for taking the time to write all this out! 😁👍

Reviewing pulls on the phone sucks, so I will check it out when I can get back to a computer.

**Comment by Cipher7** [comment]
Okay Cool! I enjoy writing , so I will surely be contributing more in
regards to many of the unfinished topics. Thank you.

**Review by zweilosec — APPROVED** [review]
Hey, this looks pretty good.  I'm going to go ahead and approve this.  There are a few minor grammatical issues but I can go through and clean those up later.  Thanks again for taking the time to help out with this!

**Comment by Cipher7** [comment]
Awesome, thanks!

**Pull request merged**
